name: test-backend

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  test:
    services:
    
      localstack:
        image: localstack/localstack
        ports:
          - "127.0.0.1:4566:4566"
          - "127.0.0.1:4510-4559:4510-4559" 
        env:
          AWS_DEFAULT_REGION: eu-central-1
          SERVICES: dynamodb
          DOCKER_HOST: unix:///var/run/docker.sock
          
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: ./backend
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Instal all app dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Run test
      working-directory: ./backend
      run: npm test
